name: mind_palace_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  file_picker: ^10.3.6  # Untuk membiarkan user memilih folder
  path_provider: ^2.1.5 # Untuk membantu mengelola path
  path: ^1.9.1          # Untuk menggabungkan path (seperti "folder/buildings")
  permission_handler: ^12.0.1 # Untuk meminta izin akses penyimpanan
  shared_preferences: ^2.5.3
  device_info_plus: ^12.2.0
  flutter_launcher_icons: ^0.14.4
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1
  archive: ^4.0.7
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/pictures/

# TAMBAHKAN BLOK KONFIGURASI DI BAWAH INI
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Sesuaikan dengan path gambar Anda

  # (Opsional tapi direkomendasikan untuk Android 8+)
  # adaptive_icon_background: "#FFFFFF" # Ganti dengan warna latar belakang
  # adaptive_icon_foreground: "assets/icon/icon-foreground.png" # Ganti dengan gambar foreground (jika ikon Anda tidak transparan)

  # Membuat apk release
  # flutter build apk --release --no-tree-shake-icons