name: mind_palace_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  file_picker: ^10.3.6  # Untuk membiarkan user memilih folder
  path_provider: ^2.1.5 # Untuk membantu mengelola path
  path: ^1.9.1          # Untuk menggabungkan path (seperti "folder/buildings")
  permission_handler: ^12.0.1 # Untuk meminta izin akses penyimpanan
  shared_preferences: ^2.5.3
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
